version: '2'

services:

  web:
    image: kurs

    ports:
      - "80:80"
    
    volumes:
      - "C:\\phpLearn\\prom_prog:/var/www/html"

    links:
      - "db:database"

  db:
    image: postgres

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=1001